#context path
server:
  servlet:
    context-path: /order
  #port
  port: 8080

# H2
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:commerce
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

# Log config
logging:
  level:
    ROOT: WARN


